GRANT USAGE ON * . * TO 'storm'@'localhost' IDENTIFIED BY 'storm' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;

CREATE DATABASE `realm` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON `realm` . * TO 'storm'@'localhost' WITH GRANT OPTION;

